"""
Kept-strategy artifact exporters.

Each accepted strategy gets three separate folders:
- strategy_file: the exact strategy.py from the kept commit
- readme_file: full readable settings and result summary
- backtesting_file: standalone adapter script with a sectioned CONFIG block
"""

from __future__ import annotations

import subprocess
from dataclasses import asdict
from pathlib import Path
from pprint import pformat

from project_config import CONFIG, ROOT
from strategy import StrategyConfig


KEPT_DIR = ROOT / "kept_strategies"


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)


def _safe_name(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in ("_", "-") else "_" for ch in value).strip("_")


def _write_root_readme() -> None:
    (KEPT_DIR / "README.md").write_text(
        """# Kept Strategies

Every kept strategy is saved in its own folder:

```text
kept_strategies/<rank>_<return>_return/
  strategy_file/
    strategy.py
  readme_file/
    README.md
  backtesting_file/
    ORB_Backtest_<rank>.py
```

Use the strategy file for the compact autoresearch project. Use the backtesting
file when you want a reusable, sectioned script with all project, execution,
risk, cost, and indicator settings in one place.
"""
    )


def _readme(rank: int, commit: str, description: str, strategy: StrategyConfig, result: dict) -> str:
    project = result.get("project", asdict(CONFIG))
    settings = asdict(strategy)
    return f"""# Kept Strategy {rank:03d}

Commit: `{commit}`

Description: {description}

## Results

| Metric | Value |
| --- | ---: |
| Return | {result['return_pct']:.4f}% |
| Max drawdown | {result['max_drawdown_pct']:.4f}% |
| Net PnL | {result['net_pnl']:.2f} |
| Final equity | {result['final_equity']:.2f} |
| Trades | {result['num_trades']} |
| Wins | {result['wins']} |
| Losses | {result['losses']} |
| Win rate | {result['win_rate_pct']:.2f}% |
| Profit factor | {result['profit_factor']:.4f} |
| Symbol buy-hold | {result['symbol_buy_hold_pct']:.4f}% |

## Project Settings

| Setting | Value |
| --- | --- |
| Strategy name | {project['strategy_name']} |
| Symbol | {project['symbol']} |
| Compare symbol | {project['compare_symbol']} |
| Symbol CSV | {project['symbol_csv']} |
| Compare CSV | {project['compare_csv']} |
| Period | {project['start_date']} to {project['end_date']} |
| Time frame | {project['timeframe']} |
| Allocation | {project['allocation']} |
| Minimum return goal | {project['min_return_pct']}% |
| Maximum drawdown goal | {project['max_drawdown_pct']}% |
| Session start | {project['session_start']} |
| Opening range minutes | {project['opening_range_minutes']} |
| Breakout start | {project['breakout_start']} |
| Square-off time | {project['square_off_time']} |
| Long allowed | {project['allow_long']} |
| Short allowed | {project['allow_short']} |
| Max open positions | {project['max_open_positions']} |

## Backtesting Assumptions

| Setting | Value |
| --- | --- |
| Candle timestamp | {project['candle_timestamp']} |
| Signal evaluation mode | {project['signal_evaluation_mode']} |
| Entry execution mode | {project['entry_execution_mode']} |
| Same-candle SL/target policy | {project['same_candle_stop_target_policy']} |
| Block same-candle re-entry | {project['block_same_candle_reentry']} |
| Allow indicator NaN trades | {project['allow_indicator_nan_trades']} |
| Gap-through stop uses open | {project['gap_through_stop_uses_open']} |
| Cost bps | {project['cost_bps']} |
| Entry slippage bps | {project['entry_slippage_bps']} |
| Stop slippage bps | {project['stop_slippage_bps']} |
| Target slippage bps | {project['target_slippage_bps']} |
| Square-off slippage bps | {project['squareoff_slippage_bps']} |
| Max trades per day | {project['max_trades_per_day']} |
| Daily loss limit pct | {project['daily_loss_limit_pct']} |
| Block after daily loss | {project['block_after_daily_loss']} |
| Minimum trades for goal | {project['min_trades_for_goal']} |

## Strategy Parameters

| Parameter | Value |
| --- | --- |
""" + "".join(f"| `{key}` | `{value}` |\n" for key, value in settings.items())


def _backtesting_script(rank: int, commit: str, description: str, strategy: StrategyConfig, result: dict) -> str:
    project_config = asdict(CONFIG)
    strategy_config = asdict(strategy)
    symbols = [CONFIG.symbol]
    strategy_file_name = f"ORB_Backtest_{rank:03d}.py"
    return f'''"""
Intraday NSE Cash Breakout Backtester + Flexible Optimizer

Generated by Autoresearch_Trading for kept strategy {rank:03d}.

This file keeps the same sectioned settings style as the larger ORB backtesting
template, but delegates execution to this project's generic engine so the logic
stays identical to the research run.
"""

# ============================================================
# 1) USER PARAMETERS - CHANGE SETTINGS HERE ONLY
# ============================================================

SYMBOLS = {symbols!r}

CONFIG = {{
    # A) Run mode
    "MODE": "Backtest",
    "RUN_OPTIMIZATION": False,
    "OPTIMIZATION_MODE": "single_strategy",

    # B) Symbols and data source
    "SYMBOLS": SYMBOLS,
    "COMPARE_SYMBOL": {CONFIG.compare_symbol!r},
    "DATA_SOURCE": "csv",
    "DATA_TIME_FRAME": {CONFIG.timeframe!r},
    "BACKTEST_TIME_FRAME": {CONFIG.timeframe!r},
    "DATA_START_DATE": {CONFIG.start_date!r},
    "DATA_END_DATE": {CONFIG.end_date!r},
    "BACKTEST_START_DATE": {CONFIG.start_date!r},
    "BACKTEST_END_DATE": {CONFIG.end_date!r},
    "SYMBOL_CSV": {CONFIG.symbol_csv!r},
    "COMPARE_CSV": {CONFIG.compare_csv!r},

    # C) Capital, sizing, and direction
    "AMOUNT_INVESTED": {CONFIG.allocation!r},
    "INITIAL_CAPITAL": {CONFIG.allocation!r},
    "MAX_POSITIONS": {CONFIG.max_open_positions!r},
    "DIRECTION_MODE": {"both" if CONFIG.allow_long and CONFIG.allow_short else "long" if CONFIG.allow_long else "short"!r},

    # D) Market timing
    "MARKET_OPEN": {CONFIG.session_start!r},
    "OPENING_RANGE_MINUTES": {CONFIG.opening_range_minutes!r},
    "STRATEGY_START": {CONFIG.breakout_start!r},
    "FORCE_EXIT": {CONFIG.square_off_time!r},

    # E) Candle timing and execution-price controls
    "CANDLE_TIMESTAMP": {CONFIG.candle_timestamp!r},
    "SIGNAL_EVALUATION_MODE": {CONFIG.signal_evaluation_mode!r},
    "ENTRY_PRICE_MODE": {CONFIG.entry_execution_mode!r},
    "SAME_CANDLE_STOP_TARGET_POLICY": {CONFIG.same_candle_stop_target_policy!r},
    "BLOCK_SAME_CANDLE_REENTRY": {CONFIG.block_same_candle_reentry!r},
    "GAP_THROUGH_STOP_USES_OPEN": {CONFIG.gap_through_stop_uses_open!r},
    "ALLOW_INDICATOR_NAN_TRADES": {CONFIG.allow_indicator_nan_trades!r},

    # F) Re-entry control
    "MAX_LONG_ENTRIES_PER_SYMBOL_PER_DAY": {strategy.max_reentries!r},
    "MAX_SHORT_ENTRIES_PER_SYMBOL_PER_DAY": {strategy.max_reentries!r},
    "MAX_TRADES_PER_DAY": {CONFIG.max_trades_per_day!r},

    # G) Costs and slippage
    "COST_BPS": {CONFIG.cost_bps!r},
    "ENTRY_SLIPPAGE_BPS": {CONFIG.entry_slippage_bps!r},
    "STOP_SLIPPAGE_BPS": {CONFIG.stop_slippage_bps!r},
    "TARGET_SLIPPAGE_BPS": {CONFIG.target_slippage_bps!r},
    "SQUAREOFF_SLIPPAGE_BPS": {CONFIG.squareoff_slippage_bps!r},

    # H) Portfolio-level risk management
    "DAILY_LOSS_LIMIT_PCT": {CONFIG.daily_loss_limit_pct!r},
    "BLOCK_NEW_TRADES_AFTER_DAILY_LOSS": {CONFIG.block_after_daily_loss!r},
    "MIN_TRADES_FOR_GOAL": {CONFIG.min_trades_for_goal!r},

    # I) Goals
    "MIN_RETURN_PCT": {CONFIG.min_return_pct!r},
    "MAX_DRAWDOWN_PCT": {CONFIG.max_drawdown_pct!r},
}}

STRATEGY_CONFIG = {pformat(strategy_config, width=100)}

PROJECT_CONFIG = {pformat(project_config, width=100)}

OPTIMIZE_PARAMS = {{
    # Keep this small unless you are doing train/test or walk-forward checks.
    "target_rr": [STRATEGY_CONFIG["target_rr"]],
    "adx_min": [STRATEGY_CONFIG["adx_min"]],
    "volume_ratio_min": [STRATEGY_CONFIG["volume_ratio_min"]],
}}


# ============================================================
# 2) IMPORTS
# ============================================================

from pathlib import Path
import itertools
import json
import sys


# ============================================================
# 3) PROJECT ADAPTER
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import engine
import project_config
from project_config import ProjectConfig
from strategy import StrategyConfig


def apply_project_config() -> None:
    cfg = ProjectConfig(**PROJECT_CONFIG)
    project_config.CONFIG = cfg
    engine.CONFIG = cfg
    engine.load_market_data.cache_clear()


def run_single_backtest(params: dict | None = None) -> dict:
    apply_project_config()
    values = dict(STRATEGY_CONFIG)
    if params:
        values.update(params)
    return engine.run_backtest(StrategyConfig(**values))


# ============================================================
# 4) BACKTEST / OPTIMIZER
# ============================================================

def optimize() -> list[dict]:
    keys = list(OPTIMIZE_PARAMS)
    results = []
    for combo in itertools.product(*(OPTIMIZE_PARAMS[key] for key in keys)):
        params = dict(zip(keys, combo))
        result = run_single_backtest(params)
        results.append({{"params": params, "result": result}})
    return sorted(
        results,
        key=lambda item: (item["result"]["goal_pass"], item["result"]["return_pct"], -item["result"]["max_drawdown_pct"]),
        reverse=True,
    )


def main() -> None:
    if CONFIG["RUN_OPTIMIZATION"]:
        rows = optimize()
        for idx, row in enumerate(rows[:20], start=1):
            result = row["result"]
            print(f"{{idx:03d}} return={{result['return_pct']:.4f}} dd={{result['max_drawdown_pct']:.4f}} trades={{result['num_trades']}} params={{row['params']}}")
        return

    result = run_single_backtest()
    print("---")
    print(f"file:               {strategy_file_name}")
    print(f"kept_rank:          {rank:03d}")
    print(f"commit:             {commit}")
    print(f"description:        {description}")
    print(f"strategy_name:      {{PROJECT_CONFIG['strategy_name']}}")
    print(f"symbol:             {{PROJECT_CONFIG['symbol']}}")
    print(f"compare:            {{PROJECT_CONFIG['compare_symbol']}}")
    print(f"period:             {{PROJECT_CONFIG['start_date']}} to {{PROJECT_CONFIG['end_date']}}")
    print(f"timeframe:          {{PROJECT_CONFIG['timeframe']}}")
    print(f"allocation:         {{PROJECT_CONFIG['allocation']:.0f}}")
    print(f"entry_mode:         {{PROJECT_CONFIG['entry_execution_mode']}}")
    print(f"return_pct:         {{result['return_pct']:.4f}}")
    print(f"max_drawdown_pct:   {{result['max_drawdown_pct']:.4f}}")
    print(f"net_pnl:            {{result['net_pnl']:.2f}}")
    print(f"num_trades:         {{result['num_trades']}}")
    print(f"win_rate_pct:       {{result['win_rate_pct']:.2f}}")
    print(f"profit_factor:      {{result['profit_factor']:.4f}}")
    print(f"goal_pass:          {{result['goal_pass']}}")
    print("strategy_config_json:")
    print(json.dumps(result["config"], indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
'''


def export_kept_strategy_artifacts(
    rank: int,
    commit: str,
    description: str,
    strategy: StrategyConfig,
    result: dict,
) -> None:
    folder = KEPT_DIR / f"{rank:03d}_{result['return_pct']:.4f}_return"
    strategy_dir = folder / "strategy_file"
    readme_dir = folder / "readme_file"
    backtesting_dir = folder / "backtesting_file"
    for target in (strategy_dir, readme_dir, backtesting_dir):
        target.mkdir(parents=True, exist_ok=True)

    show = _run(["git", "show", f"{commit}:strategy.py"])
    if show.returncode != 0:
        raise RuntimeError(show.stderr)

    (strategy_dir / "strategy.py").write_text(show.stdout)
    (readme_dir / "README.md").write_text(_readme(rank, commit, description, strategy, result))
    backtest_name = f"{_safe_name(CONFIG.strategy_name)}_Backtest_{rank:03d}.py"
    (backtesting_dir / backtest_name).write_text(_backtesting_script(rank, commit, description, strategy, result))
    _write_root_readme()
